"""Transformando categorias em uma lista

Revision ID: cdb5641fd735
Revises: fdfd3cae90dc
Create Date: 2025-11-16 15:38:05.886613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb5641fd735'
down_revision = 'fdfd3cae90dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.Text(), nullable=False))
        batch_op.drop_column('category')

    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.Text(), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('categories')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('categories')

    # ### end Alembic commands ###
